"""Stage 4: Self-contained HTML report generator."""
import base64
from datetime import datetime, timezone
from pathlib import Path


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>STEM-HAADF Structure Identification Report</title>
<style>
* {{ box-sizing: border-box; margin: 0; padding: 0; }}
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
       background: #f5f5f5; color: #333; line-height: 1.6; }}
header {{ background: #1a1a2e; color: #fff; padding: 24px 32px; }}
header h1 {{ font-size: 1.5rem; }}
.query-meta {{ font-size: 0.85rem; opacity: 0.8; margin-top: 8px; }}
.container {{ max-width: 1200px; margin: 0 auto; padding: 24px; }}
.card {{ background: #fff; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        margin-bottom: 24px; overflow: hidden; }}
.card-header {{ background: #16213e; color: #fff; padding: 16px 24px; }}
.card-header h2 {{ font-size: 1.1rem; }}
.card-header .info {{ font-size: 0.8rem; opacity: 0.75; margin-top: 4px; }}
.card-body {{ padding: 16px 24px; }}
.props {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
         gap: 8px 16px; font-size: 0.85rem; margin-bottom: 16px; }}
.props dt {{ font-weight: 600; color: #666; }}
.props dd {{ color: #111; }}
.image-grid {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr));
              gap: 16px; }}
.image-cell {{ text-align: center; border: 1px solid #eee; border-radius: 6px;
              padding: 8px; }}
.image-cell img {{ max-width: 100%; height: auto; cursor: pointer; border-radius: 4px; }}
.image-cell .label {{ font-size: 0.8rem; color: #666; margin-top: 4px; }}
.overlay {{ display: none; position: fixed; top: 0; left: 0; width: 100%; height: 100%;
           background: rgba(0,0,0,0.9); z-index: 1000; justify-content: center;
           align-items: center; }}
.overlay:target {{ display: flex; }}
.exp-image-zone {{ border: 2px dashed #ccc; border-radius: 8px; padding: 32px;
                    text-align: center; color: #999; margin-top: 24px; }}
footer {{ text-align: center; padding: 24px; color: #999; font-size: 0.8rem; }}
</style>
</head>
<body>
<header>
  <h1>STEM-HAADF Structure Identification Report</h1>
  <div class="query-meta">{query_summary}</div>
</header>
<div class="container">
{cards}
<div class="exp-image-zone">
  <p>Experimental Image Zone &mdash; place your real STEM-HAADF image here for side-by-side comparison</p>
  {exp_image_html}
</div>
</div>
<div id="lightbox" style="display:none;position:fixed;top:0;left:0;width:100%;height:100%;
     background:rgba(0,0,0,0.9);z-index:1000;cursor:pointer;"
     onclick="this.style.display='none'">
  <img id="lightbox-img" src="" style="max-width:90vw;max-height:90vh;
       position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);">
</div>
<footer>Generated by MSBatch &mdash; {timestamp}</footer>
<script>
document.querySelectorAll('.image-cell img').forEach(function(img) {{
  img.addEventListener('click', function() {{
    document.getElementById('lightbox-img').src = this.src;
    document.getElementById('lightbox').style.display = 'block';
  }});
}});
</script>
</body>
</html>"""


class Reporter:
    """Generate self-contained HTML report for human visual comparison."""

    def generate(
        self,
        candidates_json: dict,
        sim_manifest: dict,
        output_path: str | Path,
        experimental_image: str | None = None,
    ) -> str:
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        query = candidates_json.get("query", {})
        elements = query.get("elements", [])
        formula = query.get("formula", "")
        n_candidates = len(candidates_json.get("candidates", []))
        n_simulations = len(sim_manifest.get("simulations", []))

        if formula:
            qs = f"Formula: {formula} | Candidates: {n_candidates} | Simulations: {n_simulations}"
        else:
            qs = f"Elements: {', '.join(elements)} | Candidates: {n_candidates} | Simulations: {n_simulations}"

        cards_html = ""
        for cand in candidates_json.get("candidates", []):
            mid = cand["material_id"]
            images_html = ""
            for sim in sim_manifest.get("simulations", []):
                if sim["material_id"] != mid:
                    continue
                hkl = sim["miller_index"]
                hkl_str = f"({hkl[0]}{hkl[1]}{hkl[2]})"
                img_b64 = self._image_to_base64(sim["image_path"])
                if img_b64:
                    images_html += (
                        f'<div class="image-cell">'
                        f'<img src="data:image/png;base64,{img_b64}" alt="{hkl_str}">'
                        f'<div class="label">{hkl_str} slab</div></div>\n'
                    )

            # Format numbers safely
            form_e = fmt(cand.get("formation_energy_per_atom"))
            hull = fmt(cand.get("energy_above_hull"))
            bg = fmt(cand.get("band_gap"))
            ns = cand.get("n_sites", "?")

            cards_html += f"""<div class="card">
<div class="card-header">
  <h2>{cand['formula_pretty']} &mdash; {mid}</h2>
  <div class="info">Rank #{cand['rank']} | Space Group: {cand.get('space_group','?')}
  | Crystal: {cand.get('crystal_system','?')}</div>
</div>
<div class="card-body">
  <dl class="props">
    <dt>Formation Energy</dt><dd>{form_e} eV/atom</dd>
    <dt>Energy Above Hull</dt><dd>{hull} eV/atom</dd>
    <dt>Band Gap</dt><dd>{bg} eV</dd>
    <dt>N Sites</dt><dd>{ns}</dd>
  </dl>
  <div class="image-grid">{images_html}</div>
</div>
</div>\n"""

        exp_html = ""
        if experimental_image:
            img_b64 = self._image_to_base64(experimental_image)
            if img_b64:
                exp_html = f'<img src="data:image/png;base64,{img_b64}" style="max-width:400px;margin-top:12px;" alt="experimental">'

        html = HTML_TEMPLATE.format(
            query_summary=qs,
            cards=cards_html,
            exp_image_html=exp_html,
            timestamp=datetime.now(timezone.utc).isoformat(),
        )
        output_path.write_text(html, encoding="utf-8")
        return str(output_path)

    @staticmethod
    def _image_to_base64(path: str) -> str | None:
        """Read image file and encode as base64 data URI."""
        try:
            with open(path, "rb") as f:
                return base64.b64encode(f.read()).decode("ascii")
        except (FileNotFoundError, OSError):
            return None


def fmt(val):
    """Format a numeric value safely."""
    if val is None:
        return "?"
    try:
        return f"{float(val):.3f}"
    except (ValueError, TypeError):
        return str(val)
